### ISSUE TITLE
Incorrect indices? 

### ISSUE THREAD

**Issue by amitshaked** [rmitra/PS-Dataset#3]
Hey, thanks for publishing your dataset.

In the pair_patch files, the pairs are written in this format: "3.2998e+05,3.2998e+05".
If I'm not wrong, this causes two problems:
- Some of the indices are out-of-range, as in scene 20 for example (last pair). 
- The jumps are 10 patches, so we lose all the intermediate data (e.g 329981, 329982 ... ).

What do I miss? 

Thanks!

**Comment by rmitra** [comment]
Sorry about that @amitshaked updating it.

**Comment by amitshaked** [comment]
Thank you!
I think there's the same problem in the patch_info as well (in the 3d_id)

**Comment by rmitra** [comment]
Done!!!
