### ISSUE TITLE
What's the meaning of file 'pair_patch.txt'?

### ISSUE THREAD

**Issue by HencyChen** [rmitra/PS-Dataset#6]
Hi, I've download the dataset and transform all the bin into the regular jpg file so that we can visualize the data. Here I have a question.

In the folder index 11, the 0th to the 3rd patch look like they belong to the same pair (as we can also confirm this by seeing the patch_info.txt file, which the first to fourth line's first index are all 1). But in the pair_patch.txt file, I only see (0,2), (0,3) which means the 0th patch is paried with the 2nd and 3rg patch, but patch 1 should also be paired. 

Is there anything wrong in the pair_patch.txt?

Thanks.

**Comment by rmitra** [comment]
Hi, it is true the patch 0 and patch 1 belongs to the same 3D scene point. However, to make the positive pairs sufficiently varying we discarded patches which have very little geometry change.

**Comment by HencyChen** [comment]
Now I understand. Thanks for your reply.

**Comment by rmitra** [comment]
Welcome. Closing the issue
