### ISSUE TITLE
Clarifying the training procedure

### ISSUE THREAD

**Issue by rsokl** [rmitra/PS-Dataset#8]
Hello, I am interested in using your data set and am reading through the Training Procedure section (section 4.1) of your paper. I hope that you can clarify some details for me.

## Selecting nearest non-matching pairs
In it you describe a modified process for selecting valid candidates for the nearest non-matching pair. It sounds like, to do this, I would need to:
- Find two 3D points from `point_info.txt` that have at least one image in common
- Compute the image-footprint of a patch for each of those 3D points, based on the patch's reported scaling and rotation
- See if the image footprints of the two patches from the respective 3D points overlap sufficiently (50% of the unnormalized patch size)
- If they do, record them as a "valid mismatch"

Does this seem like I have a correct description of the process? Similar to `pair_patch.txt` do you have a `valid_mismatch.txt` where you have already curated these patches?

To clarify your instructions further, when you say:
> and their projections in that common image differ by 50%

Do you mean by *at least* 50% or *at most* 50%?

Could you indicated a valid pair of non-matching patches from, say, sequence 4 for me? This might help me have more confidence that I understand this properly.

## Forming batches
Regarding the way that you compose batches for training:
- How do you ensure that there are a sufficient number of valid patches for nearest non-matching pairs in a given batch? 
- Do you only draw from a single sequence to create a given batch?
- Do you have a sense for how important it is to use the valid-mismatch procedure in your training, as compared to the standard procedure in HardNet?

## Thank you!
Thanks for publishing this paper! You guys did a great job describing your dataset creation algorithm and your PS-HardNet results are truly impressive :smile:

**Comment by rmitra** [comment]
Thank you for your interest in our work,

The selection for the hardest 'valid' non-matching pair once the batch of matching pairs is formed.
The selection of non-matching pair is done from within the batch.

> * Find two 3D points from `point_info.txt` that have at least one image in common.
Given a matching pair (a_i, b_i) we find the hardest non-matching patch for a_i from the set of other b's where the 3D points corresponding to a_i, and b's should have at-least one image in common.
> * Compute the image-footprint of a patch for each of those 3D points, based on the patch's reported scaling and rotation

> * See if the image footprints of the two patches from the respective 3D points overlap sufficiently (50% of the unnormalized patch size)

**If they DO NOT overlap greater than equal to 50%, which means the appearance of a_i and the b in question are different then we consider a valid mismatch.** 

For. eg.. for batch size of 4,
matching pairs are [(a1,b1), (a2,b2), (a3,b3), (a4,b4)]

While finding the hardest for non-matching patch for a1 from {b2,b3,b4}, say the patches are ordered is 
 hardness given by {b3,b4,b2}. However, b3 has a more than 50% overlap with a1 in their common image so it is termed invalid and the next in the hardness sequence b4 is considered and so on.

A alternative strategy adopted by https://github.com/DagnyT/hardnet is to compute the descriptor distance of all b's w.r.t to a1, and transverse the b's is ascending order of distance with the valid b having a distance above a pre-determined threshold.  

> ## Forming batches
> Regarding the way that you compose batches for training:
> 
> * How do you ensure that there are a sufficient number of valid patches for nearest non-matching pairs in a given batch?

The assumption is if the 3D points corresponding to a1 and a non-matching patch is close by in the 3D space then in most cases its shares at-least one common image. If it does not we simply choose the hardest in the batch relying on the fact that they have different appearance.

> * Do you only draw from a single sequence to create a given batch?

I am not clear about what you mean by sequence, if its scene no. like 4,11,15 then yes we create the batch from only one sequence. However, better performance can be achieved if batch formation is done from the combining all the sequences.

> * Do you have a sense for how important it is to use the valid-mismatch procedure in your training, as 
compared to the standard procedure in HardNet?

Given the enormity of our data the chances of the hardest non-matching patch being invalid are in practice very less.

**Comment by ducha-aiki** [comment]
So it seems to be similar to GeoDesc https://github.com/lzx551402/geodesc

**Comment by rsokl** [comment]
@rmitra Thank you very much for the quick and detailed response. I did mean scene number when I said "sequence". 

Much appreciated!
